{% set name = "treescope" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/treescope-{{ version }}.tar.gz
  sha256: 75cff86663dfcac133b922fcc0ee9520f605dc9cbedcb34eb86a80476acbbb32

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - flit-core >=3.8,<4
    - pip
  run:
    - python >=3.10
    - numpy >=1.25.2

test:
  imports:
    - treescope
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google-deepmind/treescope#readme
  doc_url: https://treescope.readthedocs.io/
  summary: An interactive HTML pretty-printer for ML research in IPython notebooks.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
